spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://news-db:5432/news_system
    username: postgres
    password: postgres
  data:
    redis:
      host: cache-redis
      port: 6379
  cache:
    type: redis
  feign:
    client:
      comments-service:
        name: comments-service
        url: "http://comments-service:8082"
